### ISSUE TITLE
Python 3 support broke Python 2 compatibility

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/jstools#14]
This lines:
* https://github.com/camptocamp/jstools/blob/master/jstools/merge.py#L249
* https://github.com/camptocamp/jstools/blob/master/jstools/merge.py#L253
break the Python 2.7 compatibility.

They were induces through PR #13

**Comment by sbrunner** [comment]
Use the version 0.6 for Python2 :-)

**Comment by kalbermattenm** [comment]
That is what I am doing ;-)

I opened that just to let you know...
